# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

class Command(object):
    welcome = 0
    ping = 1
    cube_create = 2
    cube_status = 3
    cube_remove = 4
    player_get = 5
    player_status = 6
    player_checkin = 7
    game_ready = 8
    game_start = 9
    game_finish = 10
    response = 11
