# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CubeList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CubeList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCubeList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CubeList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CubeList
    def Cubes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from fbs.Cube import Cube
            obj = Cube()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CubeList
    def CubesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CubeList
    def CubesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def CubeListStart(builder):
    builder.StartObject(1)

def Start(builder):
    CubeListStart(builder)

def CubeListAddCubes(builder, cubes):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(cubes), 0)

def AddCubes(builder, cubes):
    CubeListAddCubes(builder, cubes)

def CubeListStartCubesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCubesVector(builder, numElems: int) -> int:
    return CubeListStartCubesVector(builder, numElems)

def CubeListEnd(builder):
    return builder.EndObject()

def End(builder):
    return CubeListEnd(builder)
