# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

class Data(object):
    NONE = 0
    Cube = 1
    CubeList = 2
    Player = 3
    PlayerList = 4
    Ticket = 5
    Response = 6
